name: build
on:
  push:
    branches:
      - build
  # pull_request:

jobs:
  install_pa_sources:
    name: install PA sources
    runs-on: ubuntu-22.04
    steps:
      # Set steps.os.outputs.image to the specific OS (e.g. 'ubuntu20')
      - name: Get operating system name and version.
        id: os
        run: echo "image=$ImageOS" >>$GITHUB_OUTPUT
        shell: bash
      - uses: actions/checkout@v3
      - name: Cache pulseaudio source
        uses: actions/cache@v3
        env:
          cache-name: cache-pulseaudio-src
        with:
          path: ~/pulseaudio.src
          key: ${{ steps.os.outputs.image }}-build-${{ env.cache-name }}
      - run: scripts/install_pulseaudio_sources_apt.sh

  build:
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     include:

    #       - CC: gcc

    #       - CC: clang

    # name: build with ${{ matrix.CC }}
    name: build
    runs-on: ubuntu-22.04
    needs: install_pa_sources
    env:
      # CC: ${{ matrix.CC }}
      CFLAGS: -Wall -Wextra -Werror

    steps:
      - name: Get operating system name and version.
        id: os
        run: echo "image=$ImageOS" >>$GITHUB_OUTPUT
        shell: bash
      - name: Fetch pulseaudio sources
        uses: actions/cache@v3
        env:
          cache-name: cache-pulseaudio-src
        with:
          path: ~/pulseaudio.src
          key: ${{ steps.os.outputs.image }}-build-${{ env.cache-name }}
      - uses: actions/checkout@v3
      - run: sudo apt-get update
      - run: sudo apt-get -yq install build-essential libpulse-dev
      - run: ./bootstrap
      - run: ./configure PULSE_DIR=~/pulseaudio.src
      - run: make
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pulseaudio-module-xrdp
          path: |
            src/.libs/*.so
            instfiles/*.sh
            instfiles/*.desktop
